### PR TITLE
Notification page

### PR DESCRIPTION
**Pull request by justinlim1**

### CODE REVIEW

**Comment by narrator0** [comment]
@justinlim1 Can you merge to the latest `main` branch?

**Comment by justinlim1** [comment]
> @justinlim1 Can you merge to the latest `main` branch?

someone has to review

**Comment by narrator0** [comment]
let me take look right now

**Comment by narrator0** [comment]
@justinlim1 you might break something when you merge 
Screen Shot 2021-03-09 at 12 08 47 AM

**Comment by justinlim1** [comment]
> @justinlim1 you might break something when you merge
> Screen Shot 2021-03-09 at 12 08 47 AM

thats used for the notification, it might just be the reference in xcode thats broken. If notification is able to load it should be good

**Comment by narrator0** [comment]
@justinlim1 I see nothing in the notification screen.
Screen Shot 2021-03-09 at 9 50 22 AM

**Comment by justinlim1** [comment]
> @justinlim1 I see nothing in the notification screen.
> Screen Shot 2021-03-09 at 9 50 22 AM

Switch yourself to mentor and add requests/mentees as mentor

**Pull request closed without merging**
